# "Release" stage used by
# From Changelog to NPM
# https://gitlab.com/GuilleW/from-changelog-to-npm

include: 'https://gitlab.com/guillew/from-changelog-to-npm/raw/v1.0.0/watch.yml'

stages:
  - test
  - Release

image: node:latest

Test and coverage:
  stage: test
  script:
    - npm ci
    - npm run coverage
