# "Release" stage used by
# From Changelog to NPM
# https://gitlab.com/GuilleW/from-changelog-to-npm

stages:
  - test
  - Release

image: node:latest

Test and coverage:
  stage: test
  script:
    - npm ci
    - npm run coverage
